config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'home' => 'home#index'
  get 'home/:query/search' => 'home#search'

end

app/models/user.rb
class User < ActiveRecord::Base


  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      name = auth.info.name
      user.first_name = name.split.first
      user.last_name = ''
      unless name.split.length < 2
        user.last_name = name.split.last
      end
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def name
    "#{self.first_name} #{self.last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @users = User.all
    if params[:search].present?
      last_name = ''
      unless params[:search].split.length < 2
        last_name = params[:search].split.last
      end
      @users = @users.where("first_name =? and last_name =?",params[:search].split.first,last_name)
    end
  end

  def search
    @first_names = User.select("first_name,last_name").where("lower(first_name) like ?","%#{params[:query].downcase}%")
    @last_names = User.select("first_name,last_name").where("lower(last_name) like ?","%#{params[:query].downcase}%")
    render json: { first_name: @first_names.as_json(:methods => [:name]),
           last_name: @last_names.as_json(:methods => [:name]) }
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="col-lg-6">
  <%= form_tag home_path, method: 'get' do %>
    <div class="input-group" id="multiple-datasets">
      <%= text_field_tag :search, params[:search],class: "form-control typeahead" ,placeholder: "Names", autocomplete: "off" %>
      <span class="input-group-btn">
        <%= button_tag "Search", name: nil,class: "btn btn-primary ",type: "submit"%>
      </span>
    </div><!-- /input-group -->
  <% end %>
</div><!-- /.col-lg-6 -->
<div class="col-lg-12 ptop-20">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>#</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Registered On</th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= user.id %></th>
        <td><%= user.first_name %> </td>
        <td><%= user.last_name %></td>
        <td><%= user.created_at.strftime('%m-%d-%Y %I:%M %p') %></td>
      </tr>
    <% end %>
    <% if @users.blank? %>
      <tr>
        <td colspan="4"> No data available </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/_footer.html.erb
<footer style="padding-top:200px;">
  <p>&copy; DemoApp 2014 by <a href="http://sachin-prasad.blogspot.in/" target="_blank" > Sachin Prasad </a></p>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar-collapse collapse navbar-responsive-collapse">
  <ul class="nav navbar-nav">
    <li><%= link_to 'Home',home_path ,'data-no-turbolink' => true %></li>
  </ul>
   <p class="navbar-text navbar-right">
    <% if current_user %>
      Welcome <strong><%= current_user.name %></strong>!
      <%= link_to "Sign out", signout_path, id: "sign_out" %>
    <% else %>
      <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
    <% end %>
    </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demoapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <%= render  'layouts/header' %>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-lg-10">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
    </div>

    <%= render "layouts/footer" %>

  </div>

</body>
</html>